(function() {var implementors = {};
implementors["coreaudio"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='coreaudio/error/audio/enum.Error.html' title='coreaudio::error::audio::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='coreaudio/error/audio_codec/enum.Error.html' title='coreaudio::error::audio_codec::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='coreaudio/error/audio_format/enum.Error.html' title='coreaudio::error::audio_format::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='coreaudio/error/audio_unit/enum.Error.html' title='coreaudio::error::audio_unit::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='coreaudio/error/enum.Error.html' title='coreaudio::error::Error'>Error</a>",];implementors["cpal"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.FormatsEnumerationError.html' title='cpal::FormatsEnumerationError'>FormatsEnumerationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.CreationError.html' title='cpal::CreationError'>CreationError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
